apiVersion: v1

kind: Pod

metadata:
  name: nginx01  # this will be the pod's name
  labels:
    app: myapp
    type: frontend

spec:
  containers:
  - name: nginxpod # this is will be container's name
    image: nginx:1.14.2
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
